const actionTypes = {
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  LOGOUT: 'LOGOUT',
  NEW_SESSION: 'NEW_SESSION',
  UPDATE_EDITOR: 'UPDATE_EDITOR',
};
export default actionTypes;
